#include "tstlsblk.h"
#include "infolsblk.h"

#include <iostream>

/**
 * 为了简化，g_strJsonLsblk来自于同目录下的lsblk.json
 */
static std::string g_strJsonLsblk = "{\n"
                                    "   \"blockdevices\": [\n"
                                    "      {\"name\":\"loop0\", \"kname\":\"loop0\", \"path\":\"/dev/loop0\", \"maj:min\":\"7:0\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"loop1\", \"kname\":\"loop1\", \"path\":\"/dev/loop1\", \"maj:min\":\"7:1\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"loop2\", \"kname\":\"loop2\", \"path\":\"/dev/loop2\", \"maj:min\":\"7:2\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"loop3\", \"kname\":\"loop3\", \"path\":\"/dev/loop3\", \"maj:min\":\"7:3\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"loop4\", \"kname\":\"loop4\", \"path\":\"/dev/loop4\", \"maj:min\":\"7:4\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"loop5\", \"kname\":\"loop5\", \"path\":\"/dev/loop5\", \"maj:min\":\"7:5\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"loop6\", \"kname\":\"loop6\", \"path\":\"/dev/loop6\", \"maj:min\":\"7:6\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"loop7\", \"kname\":\"loop7\", \"path\":\"/dev/loop7\", \"maj:min\":\"7:7\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":null, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"none\", \"rq-size\":128, \"type\":\"loop\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":null, \"tran\":null, \"subsystems\":\"block\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "      {\"name\":\"sda\", \"kname\":\"sda\", \"path\":\"/dev/sda\", \"maj:min\":\"8:0\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":\"3c2ff677\", \"pttype\":\"dos\", \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":4096, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":\"VMware_Virtual_S\", \"serial\":null, \"size\":85899345920, \"state\":\"running\", \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"mq-deadline\", \"rq-size\":254, \"type\":\"disk\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":true, \"pkname\":null, \"hctl\":\"2:0:0:0\", \"tran\":\"spi\", \"subsystems\":\"block:scsi:pci\", \"rev\":\"1.0 \", \"vendor\":\"VMware, \", \"zoned\":\"none\",\n"
                                    "         \"children\": [\n"
                                    "            {\"name\":\"sda1\", \"kname\":\"sda1\", \"path\":\"/dev/sda1\", \"maj:min\":\"8:1\", \"fsavail\":\"1789419520\", \"fssize\":\"2040373248\", \"fstype\":\"ext4\", \"fsused\":\"126803968\", \"fsuse%\":\"6%\", \"mountpoint\":\"/boot\", \"label\":\"SYSBOOT\", \"uuid\":\"ebf91b39-6b53-4a3b-b1c6-20f0e10dadca\", \"ptuuid\":\"3c2ff677\", \"pttype\":\"dos\", \"parttype\":\"0x83\", \"partlabel\":null, \"partuuid\":\"3c2ff677-01\", \"partflags\":\"0x80\", \"ra\":4096, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":2147483648, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"mq-deadline\", \"rq-size\":254, \"type\":\"part\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":true, \"pkname\":\"sda\", \"hctl\":null, \"tran\":null, \"subsystems\":\"block:scsi:pci\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "            {\"name\":\"sda2\", \"kname\":\"sda2\", \"path\":\"/dev/sda2\", \"maj:min\":\"8:2\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":\"3c2ff677\", \"pttype\":\"dos\", \"parttype\":\"0xf\", \"partlabel\":null, \"partuuid\":\"3c2ff677-02\", \"partflags\":null, \"ra\":4096, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":1024, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"mq-deadline\", \"rq-size\":254, \"type\":\"part\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":true, \"pkname\":\"sda\", \"hctl\":null, \"tran\":null, \"subsystems\":\"block:scsi:pci\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "            {\"name\":\"sda5\", \"kname\":\"sda5\", \"path\":\"/dev/sda5\", \"maj:min\":\"8:5\", \"fsavail\":\"33518477312\", \"fssize\":\"46241034240\", \"fstype\":\"ext4\", \"fsused\":\"10340405248\", \"fsuse%\":\"22%\", \"mountpoint\":\"/\", \"label\":\"SYSROOT\", \"uuid\":\"c5e6b30b-d5ab-42d6-aea0-8277cc6e1d70\", \"ptuuid\":\"3c2ff677\", \"pttype\":\"dos\", \"parttype\":\"0x83\", \"partlabel\":null, \"partuuid\":\"3c2ff677-05\", \"partflags\":null, \"ra\":4096, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":47307554816, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"mq-deadline\", \"rq-size\":254, \"type\":\"part\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":true, \"pkname\":\"sda\", \"hctl\":null, \"tran\":null, \"subsystems\":\"block:scsi:pci\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "            {\"name\":\"sda6\", \"kname\":\"sda6\", \"path\":\"/dev/sda6\", \"maj:min\":\"8:6\", \"fsavail\":\"24675864576\", \"fssize\":\"30864781312\", \"fstype\":\"ext4\", \"fsused\":\"4595134464\", \"fsuse%\":\"15%\", \"mountpoint\":\"/data\", \"label\":\"DATA\", \"uuid\":\"400d4055-6b9a-43c9-8255-a5534b046b86\", \"ptuuid\":\"3c2ff677\", \"pttype\":\"dos\", \"parttype\":\"0x83\", \"partlabel\":null, \"partuuid\":\"3c2ff677-06\", \"partflags\":null, \"ra\":4096, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":31540117504, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"mq-deadline\", \"rq-size\":254, \"type\":\"part\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":true, \"pkname\":\"sda\", \"hctl\":null, \"tran\":null, \"subsystems\":\"block:scsi:pci\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"},\n"
                                    "            {\"name\":\"sda7\", \"kname\":\"sda7\", \"path\":\"/dev/sda7\", \"maj:min\":\"8:7\", \"fsavail\":null, \"fssize\":null, \"fstype\":\"swap\", \"fsused\":null, \"fsuse%\":null, \"mountpoint\":\"[SWAP]\", \"label\":\"SWAP\", \"uuid\":\"22c11dae-0ec7-42a5-8fb8-ff1640b28683\", \"ptuuid\":\"3c2ff677\", \"pttype\":\"dos\", \"parttype\":\"0x82\", \"partlabel\":null, \"partuuid\":\"3c2ff677-07\", \"partflags\":null, \"ra\":4096, \"ro\":false, \"rm\":false, \"hotplug\":false, \"model\":null, \"serial\":null, \"size\":4897898496, \"state\":null, \"owner\":\"root\", \"group\":\"disk\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"mq-deadline\", \"rq-size\":254, \"type\":\"part\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":true, \"pkname\":\"sda\", \"hctl\":null, \"tran\":null, \"subsystems\":\"block:scsi:pci\", \"rev\":null, \"vendor\":null, \"zoned\":\"none\"}\n"
                                    "         ]\n"
                                    "      },\n"
                                    "      {\"name\":\"sr0\", \"kname\":\"sr0\", \"path\":\"/dev/sr0\", \"maj:min\":\"11:0\", \"fsavail\":null, \"fssize\":null, \"fstype\":null, \"fsused\":null, \"fsuse%\":null, \"mountpoint\":null, \"label\":null, \"uuid\":null, \"ptuuid\":null, \"pttype\":null, \"parttype\":null, \"partlabel\":null, \"partuuid\":null, \"partflags\":null, \"ra\":128, \"ro\":false, \"rm\":true, \"hotplug\":true, \"model\":\"VMware_Virtual_SATA_CDRW_Drive\", \"serial\":\"01000000000000000001\", \"size\":1073741312, \"state\":\"running\", \"owner\":\"root\", \"group\":\"cdrom\", \"mode\":\"brw-rw----\", \"alignment\":0, \"min-io\":512, \"opt-io\":0, \"phy-sec\":512, \"log-sec\":512, \"rota\":true, \"sched\":\"mq-deadline\", \"rq-size\":64, \"type\":\"rom\", \"disc-aln\":0, \"disc-gran\":0, \"disc-max\":0, \"disc-zero\":false, \"wsame\":0, \"wwn\":null, \"rand\":false, \"pkname\":null, \"hctl\":\"4:0:0:0\", \"tran\":\"sata\", \"subsystems\":\"block:scsi:pci\", \"rev\":\"1.00\", \"vendor\":\"NECVMWar\", \"zoned\":\"none\"}\n"
                                    "   ]\n"
                                    "}";

void TstLsblk::test() {
    std::cout << "test begin [" << __FILE__ << "]" << std::endl;
    TInfoLsblk infoLsBlk;
    infoLsBlk.__cjsFromJsonString(g_strJsonLsblk);

    std::cout << "blockdevices.size() : " << infoLsBlk.blockdevices.size() << std::endl;

    std::cout << "test end   [" << __FILE__ << "]\n" << std::endl;
}
